### ISSUE TITLE
Finish project setup

### ISSUE THREAD

**Issue by sbidoul** [OCA/connector-jira#1]
- [x] CLA bot
- [x] IRC bot (although there is a timeout for now)
- [ ] Twitter
- [x] Travis
- [x] Coveralls
- [x] added to OCA web site page
- [x] runbot
- [x] update OCA/maintainer-tools
- [x] repo labels

**Comment by lasley** [comment]
@sbidoul - I just activated Coveralls, I was in there activating something else and remembered seeing this email.

Are the repo labels generated with [this script](https://github.com/OCA/maintainer-tools/blob/master/tools/set_repo_labels.py)? I've been kind of curious about that, and would be happy to take care of that as well.

**Comment by jcdrubay** [comment]
Is anyone working on this? 
Are you planning to port https://apps.odoo.com/apps/7.0/bss_jira_connector/ ?

**Comment by guewen** [comment]
We planned to propose https://github.com/camptocamp/connector-jira

**Comment by alexey-pelykh** [comment]
@guewen More than a year have passed, as far as I understand bringing the codebase to OCA ended nowhere? Topic I wanted to bring up is 12.0 migration and related things

**Comment by guewen** [comment]
Hi, nothing happened during a year on our side, we have the opportunity to work on it again, for the version 11.0 though.

**Comment by jgrandguillaume** [comment]
@guewen Could you make it happen :) ?

**Comment by alexey-pelykh** [comment]
For those who are interested, see #2 and review it please

**Comment by alexey-pelykh** [comment]
We can close this?

**Comment by alexey-pelykh** [comment]
I guess so
