### ISSUE TITLE
connector_jira_tempo and hr_timesheet_sheet

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/connector-jira#14]
Seems that these to modules can/should coexist to bring in sync of Tempo concept to Odoo concept. @guewen @simahawk what's your vision?

**Comment by simahawk** [comment]
I think they could, do you see any issue? What's your use case?
TBH I don't see the benefit. The most common use case here is: you do TS in JIRA and you import them in Odoo. Which advantages do you expect?

**Comment by alexey-pelykh** [comment]
In our case, we import TS from Tempo into Odoo, then in Odoo timesheet review happens and entries become unmodifiable, but Tempo has no idea about it, unless we lock them there manually - that's what I want to automate

**Comment by leemannd** [comment]
Hello @alexey-pelykh , is there still something to be done on this topic or can we close this issue?

**Comment by alexey-pelykh** [comment]
I'd say nothing was done there to my knowledge, but likely I won't address that anytime soon
