### ISSUE TITLE
Import project tasks

### ISSUE THREAD

**Issue by dhrupkumarsingh** [OCA/connector-jira#30]
After click on 'import_project_task' button , task not get import at odoo side .

Following configuration i have made from our side .
1.  connection is already successful  (with my Jira instance).
2.  import user and import issue types also working fine.

please anyone can suggest me solution for this issue.

**Comment by alexey-pelykh** [comment]
Have you linked the project?

**Comment by dhrupkumarsingh** [comment]
![1](https://user-images.githubusercontent.com/37170541/70708462-937efd00-1d00-11ea-970b-0d930e4d920b.png)
![2](https://user-images.githubusercontent.com/37170541/70708469-97128400-1d00-11ea-92de-3bebf666c51d.png)
![3](https://user-images.githubusercontent.com/37170541/70708478-9c6fce80-1d00-11ea-8546-1c4642bf8c5c.png)


yes, I have linked my project. Above there is a screenshot of that.

**Comment by dhrupkumarsingh** [comment]
> Have you linked the project?

yes, I have linked the project. Here is a
![1](https://user-images.githubusercontent.com/37170541/70708877-8a426000-1d01-11ea-81a8-2ee2f21361f1.png)
![2](https://user-images.githubusercontent.com/37170541/70708880-8f071400-1d01-11ea-99cb-d49991468d26.png)
![3](https://user-images.githubusercontent.com/37170541/70708888-92020480-1d01-11ea-9266-099f469ccde7.png)


 screenshot of that.
