### ISSUE TITLE
Have you linked the project?

### ISSUE THREAD

**Issue by dhrupkumarsingh** [OCA/connector-jira#31]
Have you linked the project?

_Originally posted by @alexey-pelykh in https://github.com/OCA/connector-jira/issues/30#issuecomment-564954911_

**Comment by dhrupkumarsingh** [comment]
yes,  I have linked my project. Here is a screenshot of that.

![1](https://user-images.githubusercontent.com/37170541/70709647-59632a80-1d03-11ea-8d04-3d80c16da89f.png)
![2](https://user-images.githubusercontent.com/37170541/70709653-5d8f4800-1d03-11ea-9f37-59ec3fcaee4f.png)
![3](https://user-images.githubusercontent.com/37170541/70709658-62ec9280-1d03-11ea-97f9-6de1984a36ea.png)

**Comment by dhrupkumarsingh** [comment]
@alexey-pelykh Please help

**Comment by alexey-pelykh** [comment]
When you click import issues, what datetime is shown on right side of the button?
