### ISSUE TITLE
10.0 jira connector

### ISSUE THREAD

**Issue by Stephanvandenberg** [OCA/connector-jira#33]
Hi OCA maintainers,

In our Odoo 10.0 system we are currently using the CamptoCamp/Connector-Jira on branch 10.0.

However, we are experiencing a few issues and want to move to the latest connector version. I see that after the repository was moved to OCA/Connector-jira the 10.0 branch is no longer maintained. 

Is there any intention to backport to 10.0 any time in the future? Or if not and we start backporting ourselves, do you have any tips/advice that we should take into consideration?

Best regards,

Stephan

**Comment by alexey-pelykh** [comment]
@Stephanvandenberg I'm definitely not planning backporting anything to v10 in foreseeable future, not sure about the others. In what fixes are you interested in for v10 that are present in newer versions?

**Comment by Stephanvandenberg** [comment]
Hi Alexey,

In our system, most Jira tickets are interfaced to Odoo properly as tasks. But somehow not all. The Jira setup uses both software and helpdesk projects and there is also a wish to start using the 'organization' object in Jira. 

What we want to achieve is a good stable connection with Jira that retrieves all of the tasks (instead of most). We've tried a whole wide range of settings but so far we keep missing  tasks.

We were hoping to solve this by using the last version of the software, ported to be compatible with 10.0. But any advice is very much appreciated!

**Comment by Stephanvandenberg** [comment]
Hi All,

Is there any advice you can give us based on my query?
