### ISSUE TITLE
adding issue to Epic doesn't import

### ISSUE THREAD

**Issue by jcoux** [OCA/connector-jira#35]
Just copy the following issue opened previously on C2C repository.
@damdam-s opened this issue on Dec 1, 2016:

Issue is in JIRA: see https://jira.atlassian.com/browse/JSW-11149

Workaround:
When adding a `epic link` to a story/task/bug/..., edit another field like `Description` and the `epic link` will be imported to Odoo

**Comment by damdam-s** [comment]
can be closed
