### ISSUE TITLE
Can't find how to import project, task and worklog

### ISSUE THREAD

**Issue by jcoux** [OCA/connector-jira#36]
Just copy the following issue opened previously on C2C repository.
@basebasket opened this issue on Dec 28, 2016:

I 've installed the module on Odoo commnunicate 9 and had a backend configuration is running .The user is linked to user of Jira but I can't find how can I import project, task and worklog from jira and it caused me some refuse here. Could you provide some screenshots or manual for it ?

**Comment by leemannd** [comment]
Hello @basebasket,
This issue seems pretty old. I'm closing it. If you still have questions, feel free to reopen the issue.
