### ISSUE TITLE
IntegrityError: null value in column "account_id" violates not-null constraint

### ISSUE THREAD

**Issue by jcoux** [OCA/connector-jira#37]
Just copy the following issue opened previously on C2C repository.
@Dhrupesh opened this issue on Jan 27, 2019:

Hello,

As i have faced bellow error while import time log from jira to odoo 10.0

ValidationError: ('The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: account_id - account.id]', None)

Can you please tell me i have miss any configuration ?

Thanks,

**Comment by leemannd** [comment]
Closing as this seems to be old.
@Dhrupesh feel free to reopen it in case of need
