### ISSUE TITLE
[12.0] connector_jira: set tracking_disable prior to updating/creating task to avoid on-import notifications?

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/connector-jira#6]
@guewen @simahawk what do you think? or at least make it proper sender instead of account used to configure the backend

**Comment by guewen** [comment]
I think it makes sense to disable tracking yes. We have the history on Jira anyway.

**Comment by simahawk** [comment]
I agree. Is going to speed up import too.

**Comment by alexey-pelykh** [comment]
Will do then :) As soon as we finalize the migration, making PRs on PRs on PRs is generally not very good idea for the contributor :P

**Comment by alexey-pelykh** [comment]
Addressed in #9
