### ISSUE TITLE
[12.0] connector_jira: extra features

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/connector-jira#7]
@guewen @simahawk couple of questions about this module:
 * Odoo-to-Jira sync of tasks on creation was not implemented because ...?
 * Restricting editing/creation of Odoo tasks on linked projects was not implemented because ...?

**Comment by guewen** [comment]
> Odoo-to-Jira sync of tasks on creation was not implemented because ...?

Only because we didn't really need it / budget.

> Restricting editing/creation of Odoo tasks on linked projects was not implemented because ...?

Same

**Comment by alexey-pelykh** [comment]
@guewen thanks for your swift reply! Then once v12 is reviewed and merged, I'm into making new features as I need them as hell

**Comment by alexey-pelykh** [comment]
@guewen one more question, `planned_hours` on tasks in not imported due to same reason?

**Comment by guewen** [comment]
> @guewen one more question, `planned_hours` on tasks in not imported due to same reason?

Yep

**Comment by alexey-pelykh** [comment]
PRs are pending, closing. If anyone have other ideas what to import, feel free to chime in.

**Comment by iledarn** [comment]
@alexey-pelykh , why did you need `Restricting editing/creation of Odoo tasks on linked projects`
This feature is undesirable in my case btw

**Comment by iledarn** [comment]
* Odoo-to-Jira sync of tasks on creation was not implemented because ...?
* Restricting editing/creation of Odoo tasks on linked projects was not implemented because ...?

How these two can be implemented both? I do mean that if we would have Odoo-to-Jira sync (bi-directional connector) then we definitely shouldn't restrict anything

**Comment by iledarn** [comment]
Side note:
I myself prefer to have a single binding (one Odoo instance to one Jira instance, one project to one project) bi-directional connector.
I wonder about what are the benefits of having such design with "multi-bindings" projects at all

**Comment by alexey-pelykh** [comment]
> why did you need Restricting editing/creation of Odoo tasks on linked projects

@iledarn in my case, Odoo instance was a complete Jira-To-Odoo mirror, updated via sync regularly, so making changes in Odoo (altering tasks, projects, or creating new tasks in mirrored projects) was confusing for the end-users unless there would've been a bidirectional connector. But since there wasn't one (and there isn't one still) - for unidirectional mirroring, the receiving end of connector should be locked for editing to avoid data loss.
